
#Unidades
GET http://localhost:8081/membros
###

GET http://localhost:8081/membros?membroNome=Fábio Brandão Bacelar
###

GET http://localhost:8081/membros/1
###

POST http://localhost:8081/unidades
Content-Type: application/json

{
    "nome": "Ala Malhado"
}
###

POST http://localhost:8081/unidades
Content-Type: application/json

{
    "nome": "Ala"
}
###

POST http://localhost:8081/unidades
Content-Type: application/json
Accept-Language: en-US

{
    "nome": "Al"
}
###